package gvm

import chisel3._
import chisel3.experimental.ExtModule
import chisel3.util._
import top.parameters._

class GvmDutCta2Warp extends ExtModule with HasExtModuleInline {
  val io = IO(new Bundle {
    val clock               = Input(Clock())
    val warp_req_fire       = Input(UInt(1.W))      // DecoupledIO.fire
    val software_wg_id      = Input(UInt(32.W))     // pad(32)
    val software_warp_id    = Input(UInt(32.W))     // pad(32)
    val sm_id               = Input(UInt(32.W))     // pad(32)
    val hardware_warp_id    = Input(UInt(32.W))     // pad(32)
    val sgpr_base           = Input(UInt(32.W))     // pad(32)
    val vgpr_base           = Input(UInt(32.W))     // pad(32)
    val wg_slot_id_in_warp_sche = Input(UInt(32.W)) // pad(32)
  })

  setInline("GvmDutCta2Warp.sv",
    s"""
    |// generated by Chisel ExtModule
    |module GvmDutCta2Warp (
    |  input  wire        io_clock,
    |  input  wire        io_warp_req_fire,
    |  input  wire [31:0] io_software_wg_id,
    |  input  wire [31:0] io_software_warp_id,
    |  input  wire [31:0] io_sm_id,
    |  input  wire [31:0] io_hardware_warp_id,
    |  input  wire [31:0] io_sgpr_base,
    |  input  wire [31:0] io_vgpr_base,
    |  input  wire [31:0] io_wg_slot_id_in_warp_sche
    |);
    |
    |  import "DPI-C" function void c_GvmDutCta2Warp(
    |    input int software_wg_id,
    |    input int software_warp_id,
    |    input int sm_id,
    |    input int hardware_warp_id,
    |    input int sgpr_base,
    |    input int vgpr_base,
    |    input int wg_slot_id_in_warp_sche
    |  );
    |
    |  always @(posedge io_clock) begin
    |    if (io_warp_req_fire) begin
    |      c_GvmDutCta2Warp(
    |        io_software_wg_id,
    |        io_software_warp_id,
    |        io_sm_id,
    |        io_hardware_warp_id,
    |        io_sgpr_base,
    |        io_vgpr_base,
    |        io_wg_slot_id_in_warp_sche
    |      );
    |    end
    |  end
    |endmodule
    """.stripMargin)
}

class GvmDutInsnDispatch extends ExtModule with HasExtModuleInline {
  val io = IO(new Bundle {
    val clock         = Input(Clock())
    val dispatch_fire = Input(UInt(num_warp.W))
    val sm_id          = Input(UInt((num_warp * 32).W))
    val hardware_warp_id = Input(UInt((num_warp * 32).W)) 
    val pc             = Input(UInt((num_warp * 32).W))
    val instr          = Input(UInt((num_warp * 32).W))
    val dispatch_id    = Input(UInt((num_warp * 32).W))
    val is_extended    = Input(UInt(num_warp.W))
  })

  setInline(
    "GvmDutInsnDispatch.sv", 
    s"""
    |// generated by Chisel ExtModule
    |module GvmDutInsnDispatch (
    |  input  wire        io_clock,
    |  input  wire [${num_warp-1}:0] io_dispatch_fire,
    |  input  wire [${num_warp*32-1}:0] io_sm_id,
    |  input  wire [${num_warp*32-1}:0] io_hardware_warp_id,
    |  input  wire [${num_warp*32-1}:0] io_pc,
    |  input  wire [${num_warp*32-1}:0] io_instr,
    |  input  wire [${num_warp*32-1}:0] io_dispatch_id,
    |  input  wire [${num_warp-1}:0] io_is_extended
    |);
    |
    |  import "DPI-C" function void c_GvmDutInsnDispatch(
    |    input int sm_id,
    |    input int hardware_warp_id,
    |    input int pc,
    |    input int instr,
    |    input int dispatch_id,
    |    input bit is_extended
    |  );
    |
    |  integer i;
    |  always @(posedge io_clock) begin
    |    for (i = 0; i < ${num_warp}; i = i + 1) begin
    |      if (io_dispatch_fire[i]) begin
    |        c_GvmDutInsnDispatch(
    |          io_sm_id[32*i+:32],
    |          io_hardware_warp_id[32*i+:32],
    |          io_pc[32*i +:32],
    |          io_instr[32*i +:32], 
    |          io_dispatch_id[32*i +:32],
    |          io_is_extended[i]);
    |      end
    |    end
    |  end
    |endmodule
    """.stripMargin)
}


class GvmDutXRegWriteback extends ExtModule with HasExtModuleInline {
  val io = IO(new Bundle {
    val clock              = Input(Clock())
    val fire               = Input(UInt(1.W))            // decoupledIO fire
    val sm_id              = Input(UInt(32.W))           // pad(32)
    val rd                  = Input(UInt(32.W))           // int
    val is_scalar_wb       = Input(UInt(1.W))            // bit
    val reg_idx            = Input(UInt(32.W))           // pad(32)
    val hardware_warp_id   = Input(UInt(32.W))           // pad(32)
    val pc                  = Input(UInt(32.W))           // int
    val inst                = Input(UInt(32.W))           // int
    val dispatch_id        = Input(UInt(32.W))           // int
  })

  setInline("GvmDutXRegWriteback.sv",
    s"""
    |// generated by Chisel ExtModule
    |module GvmDutXRegWriteback (
    |  input  wire        io_clock,
    |  input  wire        io_fire,
    |  input  wire [31:0] io_sm_id,
    |  input  wire [31:0] io_rd,
    |  input  wire        io_is_scalar_wb,
    |  input  wire [31:0] io_reg_idx,
    |  input  wire [31:0] io_hardware_warp_id,
    |  input  wire [31:0] io_pc,
    |  input  wire [31:0] io_inst,
    |  input  wire [31:0] io_dispatch_id
    |);
    |
    |  import "DPI-C" function void c_GvmDutXRegWriteback(
    |    input int   sm_id,
    |    input int   rd,
    |    input bit   is_scalar_wb,
    |    input int   reg_idx,
    |    input int   hardware_warp_id,
    |    input int   pc,
    |    input int   inst,
    |    input int   dispatch_id
    |  );
    |
    |  always @(posedge io_clock) begin
    |    if (io_fire) begin
    |      c_GvmDutXRegWriteback(
    |        io_sm_id,
    |        io_rd,
    |        io_is_scalar_wb,
    |        io_reg_idx,
    |        io_hardware_warp_id,
    |        io_pc,
    |        io_inst,
    |        io_dispatch_id
    |      );
    |    end
    |  end
    |endmodule
    """.stripMargin)
}


class GvmDutXReg extends ExtModule with HasExtModuleInline {
  val io = IO(new Bundle {
    val clock          = Input(Clock())
    // val num_sm         = Input(UInt(32.W))
    val sm_id          = Input(UInt(32.W))
    // val num_bank       = Input(UInt(32.W))
    // val num_sgpr_slots = Input(UInt(32.W))
    val xbanks         = Input(UInt((NUMBER_SGPR_SLOTS * 32).W))
  })

  setInline("GvmDutXReg.sv",
    s"""
    |// generated by Chisel ExtModule
    |module GvmDutXReg (
    |  input  wire               io_clock,
    |  input  wire [31:0]        io_sm_id,
    |  input  wire [${(NUMBER_SGPR_SLOTS * 32) - 1}:0] io_xbanks
    |);
    |
    |  import "DPI-C" function void c_GvmDutXReg(
    |    input int num_sm,
    |    input int sm_id,
    |    input int num_bank,
    |    input int num_sgpr_slots,
    |    input int xbanks_word,
    |    input int xbanks_word_idx
    |  );
    |
    |  integer i;
    |  always @(posedge io_clock) begin
    |    // 每个时钟周期都把最新的 xbank 状态传给 DPI
    |    for (i = 0; i < ${NUMBER_SGPR_SLOTS}; i = i + 1) begin
    |    c_GvmDutXReg(
    |      ${num_sm},
    |      io_sm_id,
    |      ${num_bank},
    |      ${NUMBER_SGPR_SLOTS},
    |      io_xbanks[32*i +:32],
    |      i
    |    );
    |    end
    |  end
    |endmodule
    """.stripMargin)
}

class GvmDutVRegWriteback extends ExtModule with HasExtModuleInline {
  val io = IO(new Bundle {
    val clock              = Input(Clock())
    val fire               = Input(UInt(1.W))            // decoupledIO fire
    val sm_id              = Input(UInt(32.W))           // pad(32)
    val rd                 = Input(UInt((num_thread * xLen).W))  // UInt - 向量数据转换为一维信号
    val is_vector_wb       = Input(UInt(1.W))            // bit - 向量写回使能
    val reg_idx            = Input(UInt(32.W))           // pad(32)
    val hardware_warp_id   = Input(UInt(32.W))           // pad(32)
    val pc                 = Input(UInt(32.W))           // int
    val inst               = Input(UInt(32.W))           // int
    val dispatch_id        = Input(UInt(32.W))           // int
    val wvd_mask           = Input(UInt(num_thread.W))   // 向量写回掩码转换为一维信号
  })

  setInline("GvmDutVRegWriteback.sv",
    s"""
    |// generated by Chisel ExtModule
    |module GvmDutVRegWriteback (
    |  input  wire        io_clock,
    |  input  wire        io_fire,
    |  input  wire [31:0] io_sm_id,
    |  input  wire [${num_thread * xLen - 1}:0] io_rd,
    |  input  wire        io_is_vector_wb,
    |  input  wire [31:0] io_reg_idx,
    |  input  wire [31:0] io_hardware_warp_id,
    |  input  wire [31:0] io_pc,
    |  input  wire [31:0] io_inst,
    |  input  wire [31:0] io_dispatch_id,
    |  input  wire [${num_thread - 1}:0] io_wvd_mask
    |);
    |
    |  import "DPI-C" function void c_GvmDutVRegWriteback(
    |    input int   sm_id,
    |    input int   rd_data,
    |    input bit   is_vector_wb,
    |    input int   reg_idx,
    |    input int   hardware_warp_id,
    |    input int   pc,
    |    input int   inst,
    |    input int   dispatch_id,
    |    input bit   wvd_mask,
    |    input int   thread_idx
    |  );
    |
    |  integer i;
    |  always @(posedge io_clock) begin
    |    if (io_fire) begin
    |      for (i = 0; i < ${num_thread}; i = i + 1) begin
    |        c_GvmDutVRegWriteback(
    |          io_sm_id,
    |          io_rd[${xLen}*i +:${xLen}],
    |          io_is_vector_wb,
    |          io_reg_idx,
    |          io_hardware_warp_id,
    |          io_pc,
    |          io_inst,
    |          io_dispatch_id,
    |          io_wvd_mask[i],
    |          i
    |        );
    |      end
    |    end
    |  end
    |endmodule
    """.stripMargin)
}

class GvmDutBarrierDone extends ExtModule with HasExtModuleInline {
  val io = IO(new Bundle {
    val clock          = Input(Clock())
    val bar_done_fire  = Input(UInt(1.W))
    val sm_id          = Input(UInt(32.W))
    val wg_slot_id     = Input(UInt(32.W))
    val pc             = Input(UInt(32.W))
    val inst           = Input(UInt(32.W))
    val dispatch_id    = Input(UInt(32.W))
  })

  setInline("GvmDutBarrierDone.sv",
    s"""
    |// generated by Chisel ExtModule
    |module GvmDutBarrierDone (
    |  input  wire        io_clock,
    |  input  wire        io_bar_done_fire,
    |  input  wire [31:0] io_sm_id,
    |  input  wire [31:0] io_wg_slot_id,
    |  input  wire [31:0] io_pc,
    |  input  wire [31:0] io_inst,
    |  input  wire [31:0] io_dispatch_id
    |);
    |
    |  import "DPI-C" function void c_GvmDutBarrierDone(
    |    input int sm_id,
    |    input int wg_slot_id,
    |    input int pc,
    |    input int inst,
    |    input int dispatch_id
    |  );
    |
    |  always @(posedge io_clock) begin
    |    if (io_bar_done_fire) begin
    |      c_GvmDutBarrierDone(
    |        io_sm_id,
    |        io_wg_slot_id,
    |        io_pc,
    |        io_inst,
    |        io_dispatch_id
    |      );
    |    end
    |  end
    |endmodule
    """.stripMargin)
}